### ISSUE TITLE
Writte README.md file

### ISSUE THREAD

**Issue by Lookingfor00** [Lookingfor00/Meet-Africans#30]
document the project, the file should contain:
- Preview section for desktop and mobile version
- Table of content sections
- Live URL demo section ([here is a link to the Live demo](https://meet-africans.netlify.app/))

**NB: the more unspecified topics can/should be added**

**Comment by ebuka1-anthony** [comment]
ok, i'm working on it

**Comment by Lookingfor00** [comment]
Great! Thanks @ebuka1-anthony 👍 🥇 

I will assign you this issue.

**Comment by ebuka1-anthony** [comment]
thanks
